version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-examclass
    ports:
      - '6500:5432'
    volumes:
      - progresExamDB:/var/lib/postgresql/data
    env_file:
      - ./.env
  pgadmin:
    container_name: pgadmin4_container-examclass
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  redis:
    image: redis:alpine
    container_name: redis-examclass
    ports:
      - '6379:6379'
    volumes:
      - redisExamDB:/data
volumes:
  progresExamDB:
  redisExamDB: