version: '3'
services:
  web:
    image: 'imajkumar/kumardhubi-service:latest'
    ports:
      - '3000:3000'
  postgres:
    image: 'postgres:latest'
    container_name: postgres-examclass
    ports:
      - '5432:5432'
    volumes:
      - 'progresExamDB:/var/lib/postgresql/data'
    env_file:
      - ./.env
  redis:
    image: 'redis:alpine'
    container_name: redis-examclass
    ports:
      - '6379:6379'
    volumes:
      - 'redisExamDB:/data'
volumes:
  progresExamDB: null
  redisExamDB: null
